version: "2"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=your-cloudflare-api-key
      - ZONE=domain.com
      - SUBDOMAIN= # optional
      - PROXIED= # optional
