version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - $HOST_PORT:80
    volumes:
      - /home/media/AudioLibros:/audiobooks
      - /home/media/podcast:/podcasts
      - /home/media/audiobookshelf/appconfig:/config
      - /home/media/audiobookshelf/appmetadata:/metadata
    restart: unless-stopped
