---
version: "3"
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "$HOST_PORT:5800"
    volumes:
      - "/home/notolac/jdownloader:/config:rw"
      - "/media/raid/multimedia/radarr-downloads:/output:rw"
