version: "3"
services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - guacnet

  postgres-guacamole:
    image: postgres
    container_name: postgres-guacamole
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole-oficial
    depends_on:
      - guacd
      - postgres-guacamole
    environment:
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      GUACD_HOSTNAME: guacd # Hostname del contenedor guacd
      GUACD_PORT: 4822 # Puerto estándar de guacd
      POSTGRESQL_HOSTNAME: postgres-guacamole # Hostname del contenedor postgres
      POSTGRESQL_PORT: 5432 # Puerto estándar de PostgreSQL
    ports:
      - "$HOSTPORT:8080"
    networks:
      - guacnet
    volumes:
      - guacamole_data:/etc/guacamole # Asumiendo que Guacamole guarda datos importantes aquí

networks:
  guacnet:
    driver: bridge

volumes:
  postgres_data:
  guacamole_data:
