version: "3"
services:
  guacamole:
    image: abesnier/guacamole
    restart: always
    container_name: guacamole
    volumes:
      - Guacamole-NFS:/config
    ports:
      - 8194:8080
    environment:
      - EXTENSIONS=auth-totp #optional 2FA
volumes:
  Guacamole-NFS:
    external: true