version: "3"
services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - guacnet
    ports:
      - "4822:4822"

  postgres-guacamole:
    image: postgres:16.3
    container_name: guacamoledb
    environment:
      - POSTGRES_PASSWORD:$POSTGRES_PASSWORD
      - POSTGRES_DB:$POSTGRES_DB
      - POSTGRES_USER:$POSTGRES_USER
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole-oficial
    depends_on:
      - guacd
      - postgres-guacamole
    environment:
      - POSTGRESQL_HOSTNAME: "postgres-guacamole" # Hostname del contenedor postgres
      - POSTGRESQL_PORT: "5432" # Puerto estándar de PostgreSQL
      - POSTGRESQL_DATABASE:$POSTGRESQL_DATABASE
      - POSTGRESQL_USER:$POSTGRESQL_USER
      - POSTGRESQL_PASSWORD:$POSTGRESQL_PASSWORD
      - GUACD_HOSTNAME: "guacd" # Hostname del contenedor guacd
      - GUACD_PORT: "4822" # Puerto estándar de guacd
    ports:
      - "$HOSTPORT:8080"
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge

volumes:
  postgres_data:
