---
version: "2"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - UMASK_SET=022 # control permissions of files and directories created by Radarr
      - TZ=Europe/Madrid # Specify a timezone to use EG Europe/London, this is required for Radarr
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - /home/plex:/movies # Location of Movie library on disk (See note in Application setup)
      - /home/media/radarr-downloads:/downloads # Location of download managers output directory (See note in Application setup)
      - /home/notolac/radarr-data:/config # Database and Radarr configs
    ports:
      - 7878:7878/tcp # The port for the Radarr webinterface
