version: "3.8"

services:
  rclone_sync:
    image: rclone/rclone:latest
    container_name: rclone_sync
    volumes:
      - /home/notolac/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
      - /home/notolac/scripts/rclone_entrypoint.sh:/entrypoint.sh:ro # Script para comandos rclone
      - /media/raid/multimedia:/data/multimedia
      - /media/raid/Plex:/data/Plex
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    restart: unless-stopped
