version: "3.8"

services:
  rclone_sync:
    image: rclone/rclone:latest
    container_name: rclone_sync
    volumes:
      - /home/notolac/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
      - /home/media/multimedia:/data/multimedia
      - /home/media/Plex:/data/Plex
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "rclone sync /data/multimedia chiguire-bot-gdrive:/path/in/shared/drive/multimedia && rclone sync /data/Plex chiguire-bot-gdrive:/path/in/shared/drive/Plex",
      ]
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    user: "${UID}:${GID}"
    restart: unless-stopped
