version: "3.1"

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - $HOST_PORT:80
    environment:
      WORDPRESS_DB_HOST: db-wp #use the same name as the database service
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER #user
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD #password
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - wordpress:/var/www/html

  db-wp:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER #user
      MYSQL_PASSWORD: $MYSQL_PASSWORD #password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db-wp:/var/lib/mysql

volumes:
  wordpress:
  db-wp:
