---
version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 8080:80
      - 8181:81
      - 443:443
    volumes:
      - /home/notolac/nginx-proxy-manager/data:/data
      - /home/notolac/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /home/notolac/nginx-proxy-manager/_hsts.conf:/app/templates/_hsts.conf:ro #change to the location of your choice
