---
version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 8080:80
      - 8181:81
      - 443:443
    volumes:
      - ./nginx-proxy-manager:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./hsts/_hsts.conf:/app/templates/_hsts.conf:ro
